# Write a ready-to-use .env for the local producer & dashboard. After
# `terraform apply`, both apps pick up Confluent Cloud connectivity from this
# file with no manual secret handling.
resource "local_file" "dotenv" {
  filename        = "${path.module}/../.env"
  file_permission = "0600"
  content         = <<-EOT
    # Generated by Terraform — do not edit by hand. Re-run `terraform apply` to refresh.
    BOOTSTRAP_SERVERS=${replace(confluent_kafka_cluster.standard.bootstrap_endpoint, "SASL_SSL://", "")}
    KAFKA_API_KEY=${confluent_api_key.kafka.id}
    KAFKA_API_SECRET=${confluent_api_key.kafka.secret}
    SCHEMA_REGISTRY_URL=${data.confluent_schema_registry_cluster.sr.rest_endpoint}
    SCHEMA_REGISTRY_API_KEY=${confluent_api_key.schema_registry.id}
    SCHEMA_REGISTRY_API_SECRET=${confluent_api_key.schema_registry.secret}
  EOT
}
